<a href="https://colab.research.google.com/github/gourynandana/Srishti/blob/main/DAY4/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [2]:
import numpy as np
arr=np.array([1,2,3])
print(type(arr))


<class 'numpy.ndarray'>


In [5]:
import numpy as np
arr=np.array([1,2,3,4])
b=arr.shape
print(b)


(4,)


In [6]:
import numpy as np
arr=np.array([[1,2],[3,4]])
print(arr)


[[1 2]
 [3 4]]


In [7]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [9]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)
